import type { Metadata, Viewport } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/navbar/Navbar';
import PlayerBar from '@/components/player/playerBar/PlayerBar';
import Wrapper from '@/components/wrapper/Wrapper';
import MainSection from '@/components/mainSection/mainSection';

const inter = Inter({ subsets: ['greek'] });

export const metadata: Metadata = {
  title: 'ListenBro',
  description: 'Generated by create next app',
  manifest: '/manifest.json',
  appleWebApp: {
    statusBarStyle: 'black-translucent',
  },
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  viewportFit: 'cover',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="dark">
      <body className={inter.className}>
        <Wrapper>
          <Navbar />
          <MainSection>{children}</MainSection>
          <PlayerBar />
        </Wrapper>
      </body>
    </html>
  );
}
