import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/navbar/Navbar';
import Player from '@/components/player/Player';
import Wrapper from '@/components/wrapper/Wrapper';
import MainSection from '@/components/mainSection/mainSection';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'ListenBroT',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <link rel="manifest" href="/manifest.json" />
      <meta
        name="viewport"
        content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
      />
      <meta name="HandheldFriendly" content="true" />
      <link rel="apple-touch-icon" href="/icon-256x256.png" />
      <body className={inter.className}>
        <Wrapper>
          <Navbar />
          <MainSection>{children}</MainSection>
          <Player />
        </Wrapper>
        <div id={'overlays'}></div>
      </body>
    </html>
  );
}
